server:
  port: 8081  #数据库端口号
  servlet:
    context-path: /zhuo


#  数据库连接驱动
spring:
  application:
    name: lastwhisper-mybatis-plus
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blackBeaconPlus?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Zhuodada



mybatis:
#    MyBatis映射文件配置
  mapper-locations: classpath:mapper/*.xml
  #  别名的配置
  type-aliases-package: com.zhuo.springboot_mybatis_plus_mysql.entity


#MyBatis分页插件
pagehelper:
  helper-dialect: mysql
  params: countSql
  reasonable: false
  support-methods-arguments: true



  #log4j2 文件地址
logging:
  config: classpath:log4j2.xml


#mybatis-plus:
#  config-location: classpath:mapper/*.xml


